@hostname = localhost
@port = 3000
@host = {{hostname}}:{{port}}
@contentType = application/json

###
GET http://{{host}}

###
POST http://localhost:{{port}} HTTP/1.1
Content-Type: {{contentType}}

{
    "name" : "user-1",
    "password" : 123123
}

